@startuml "AQ Cloud Dashboard Component Diagram"
title "Component Diagram for AQ Cloud Dashboard"
component "AQ Data API" as AQDataAPI{
    json SampleDataEntry{
        "city": "Goa",
        "Point": {
            "latitude": 15.2993,
            "longitude": 74.1240
        },
        "date": "2023-10-01",
        "AQI": 85,
        "pollutants": {
            "PM2.5": 35,
            "PM10": 50,
            "NO2": 20,
            "SO2": 10,
            "CO": 0.5,
            "O3": 30
        }
    }
}

interface "AQI API Get Endpoint" as AQIAPI

cloud "Cloud Server" {
    component "Machine Learning Inference Service" as MLService{
        component "AQI Prediction Model" as AQIPredModel
    }
    interface "Predict AQI" as AQIPredAPI
    database "AQ Database" as DB
    interface "Database CURD API" as DBAPI

    component "AQ Data Fetcher API" as DataAPI
}

node "Hosted Server" {
    component "Web Application" as WebApp
}

AQDataAPI --> AQIAPI : "Fetch AQI Data"
AQIAPI --> DataAPI : "Provide AQI Data"
DataAPI --> DBAPI : "Store AQI Data"
DBAPI --> DB : "CURD Operations"
WebApp --> DBAPI : "Fetch AQI Data"
MLService --> DBAPI : "Fetch Historical Data"
MLService --> AQIPredAPI : "Provide AQI Predictions"
WebApp --> AQIPredAPI : "Get AQI Predictions"
@enduml
