@startuml "AQI Data Dashboard"
component "DataAPI" as DataAPI
component "Frontend" as Frontend
component "Inference Task" as InferenceService
cloud "Open Metro" as OpenMetro

database "AQI Database" as AQIDB{
}


DataAPI --> OpenMetro : "1. Request AQI Data"
OpenMetro --> DataAPI : "2. Return AQI Data"
DataAPI --> AQIDB : "3. Insert New AQI Data"
AQIDB --> InferenceService : "4. Get Data For Inference"
InferenceService --> AQIDB  : "5. Return Predictions Data"
AQIDB --> Frontend : "6. Get Data"